build:
	pdflatex lostvaults.tex
	pdflatex lostvaults.tex
	pdflatex lostvaults.tex
	mv lostvaults.pdf ../Proposal/Lost\ Vaults\ Proposal.pdf
	rm lostvaults.toc lostvaults.aux
	pdflatex networkmessages.tex
	pdflatex networkmessages.tex
	pdflatex networkmessages.tex
	mv networkmessages.pdf ../Proposal/Network\ Messages.pdf
	rm networkmessages.aux
